CREATE SEQUENCE closedbookroom.book_search_history_id_seq START WITH 1;

CREATE TABLE IF NOT EXISTS closedbookroom.book_search_history (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE closedbookroom.book_search_history_id_seq PRIMARY KEY ,
  ctime TIMESTAMP WITH TIME ZONE,
  username VARCHAR(256) NOT NULL,
  provider_id VARCHAR(256) NOT NULL,
  request_json LONGVARCHAR NOT NULL,
  bookmark BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE IF NOT EXISTS closedbookroom.book_search_history_to_bookmark_map (
  history_id BIGINT PRIMARY KEY,
  bookmark_id BIGINT NOT NULL
);

CREATE UNIQUE INDEX closedbookroom.ux_book_search_history_to_bookmark_map
  ON closedbookroom.book_search_history_to_bookmark_map(history_id, bookmark_id);

