CREATE SCHEMA IF NOT EXISTS closedbookroom;

CREATE SEQUENCE closedbookroom.user_id_seq START WITH 1;

CREATE TABLE IF NOT EXISTS closedbookroom.user (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE closedbookroom.user_id_seq PRIMARY KEY ,
  username VARCHAR(256) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  role VARCHAR(256) NOT NULL,
  active BOOLEAN DEFAULT TRUE NOT NULL
);

-- $ perl -MCrypt::Bcrypt::Easy -MModern::Perl -e'say bcrypt->crypt("test")'
-- test : test
-- testlocked : test
INSERT INTO closedbookroom.user (username, password, role, active) VALUES (
    'test', '$2a$08$2Ys20g//PwJ/yeeccghh4unGr8ndtrgj5.xc.QEHnVM.AC/irFPWG', 'ROLE_USER', TRUE);
INSERT INTO closedbookroom.user (username, password, role, active) VALUES (
    'testlocked', '$2a$08$2Ys20g//PwJ/yeeccghh4unGr8ndtrgj5.xc.QEHnVM.AC/irFPWG', 'ROLE_USER', FALSE);

-- admin : admin
INSERT INTO closedbookroom.user (username, password, role, active) VALUES (
    'admin', '$2a$08$BZn5/ycYpQfz5bAFr/VwfeNNkqoe6gPzjCxDaGZA1bVmF.ZfMcbYy', 'ROLE_ADMIN', TRUE);


