closed-book-room:
  kakao-api:
    rest-api-key: 9b7471bbb7d0d1405fa11afbca9f4856

spring:
  application:
    name: closedbookroom
  flyway:
    locations:  db/migration/{vendor}

  datasource:
    url:  jdbc:hsqldb:mem:${spring.application.name}

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        default_schema: ${spring.application.name}
    hibernate:
      ddl-auto: none

flyway:
  enabled: true
  checkLocation: true
  locations: classpath:db/migration
  schemas: ${spring.application.name}